[mapper]
"Accession" = "Proteins"
"Peptide" = "Sequence"
"z" = "Charge"

[condition_mapper]
"LFQ_Astral_DDA_15min_50ng_Condition_A_REP1 Normalized Area" = "A"
"LFQ_Astral_DDA_15min_50ng_Condition_A_REP2 Normalized Area" = "A"
"LFQ_Astral_DDA_15min_50ng_Condition_A_REP3 Normalized Area" = "A"
"LFQ_Astral_DDA_15min_50ng_Condition_B_REP1 Normalized Area" = "B"
"LFQ_Astral_DDA_15min_50ng_Condition_B_REP2 Normalized Area" = "B"
"LFQ_Astral_DDA_15min_50ng_Condition_B_REP3 Normalized Area" = "B"

[run_mapper]
"LFQ_Astral_DDA_15min_50ng_Condition_A_REP1 Normalized Area" = "Condition_A_Sample_Alpha_01"
"LFQ_Astral_DDA_15min_50ng_Condition_A_REP2 Normalized Area" = "Condition_A_Sample_Alpha_02"
"LFQ_Astral_DDA_15min_50ng_Condition_A_REP3 Normalized Area" = "Condition_A_Sample_Alpha_03"
"LFQ_Astral_DDA_15min_50ng_Condition_B_REP1 Normalized Area" = "Condition_B_Sample_Alpha_01"
"LFQ_Astral_DDA_15min_50ng_Condition_B_REP2 Normalized Area" = "Condition_B_Sample_Alpha_02"
"LFQ_Astral_DDA_15min_50ng_Condition_B_REP3 Normalized Area" = "Condition_B_Sample_Alpha_03"

[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[modifications_parser]
"parse_column" = "Sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern"="(?<=\\().+?(?=\\))"
"modification_dict" = {"+57.02" = "Carbamidomethyl", "+15.99" = "Oxidation", "-17.026548" = "Gln->pyro-Glu", "-18.010565" = "Glu->pyro-Glu", "+42.01" = "Acetyl"}

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = false
