[mapper]
"FG.LabeledSequence" = "Sequence"
"R.FileName" = "Raw file"
"FG.Charge" = "Charge"
"EG.TotalQuantity (Settings)" = "Intensity"
"PG.ProteinGroups" = "Proteins"

[condition_mapper]
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_240pg_10pg_H_Y_r1" = "A"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_240pg_10pg_H_Y_r2" = "A"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_240pg_10pg_H_Y_r3" = "A"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_200pg_50pg_H_Y_r1" = "B"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_200pg_50pg_H_Y_r2" = "B"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_200pg_50pg_H_Y_r3" = "B"

[run_mapper]
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_240pg_10pg_H_Y_r1" = "Condition_A_Sample_1"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_240pg_10pg_H_Y_r2" = "Condition_A_Sample_2"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_240pg_10pg_H_Y_r3" = "Condition_A_Sample_3"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_200pg_50pg_H_Y_r1" = "Condition_B_Sample_1"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_200pg_50pg_H_Y_r2" = "Condition_B_Sample_2"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_200pg_50pg_H_Y_r3" = "Condition_B_Sample_3"

[species_mapper]
"_YEAST" = "YEAST"
"_HUMAN" = "HUMAN"

[modifications_parser]
"parse_column" = "Sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern" = "\\[(.*?)\\]"
"modification_dict" = {"[oxidation (m)]" = "Oxidation", "[acetyl (protein n-term)]" = "Acetyl", "[carbamidomethyl (c)]" = "Carbamidomethyl"}

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = true
