[mapper]
"Sequence" = "Sequence"
"Raw file" = "Raw file"
"Proteins" = "Proteins"
"Modified sequence" = "Modified sequence"
"Charge" = "Charge"

[condition_mapper]
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01" = "A"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02" = "A"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03" = "A"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01" = "B"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02" = "B"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03" = "B"

[run_mapper]
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01" = "Condition_A_Sample_Alpha_01"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02" = "Condition_A_Sample_Alpha_02"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03" = "Condition_A_Sample_Alpha_03"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01" = "Condition_B_Sample_Alpha_01"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02" = "Condition_B_Sample_Alpha_02"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03" = "Condition_B_Sample_Alpha_03"

[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[modifications_parser]
"parse_column" = "Modified sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern" = "\\([^()]*\\)|\\([^()]*\\([^()]*\\)[^()]*\\)"
"modification_dict" = {"(ox)" = "Oxidation", "(ac)" = "Acetyl", "(oxidation (m))" = "Oxidation", "(acetyl (protein n-term))" = "Acetyl"}

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = true
