[mapper]
"Modified.Sequence" = "Sequence"
"Run" = "Raw file"
"Protein.Names" = "Proteins"
"Precursor.Charge" = "Charge"
"Precursor.Quantity" = "Intensity"

[condition_mapper]
"LFQ_Astral_DIA_15min_50ng_Condition_A_REP1" = "A"
"LFQ_Astral_DIA_15min_50ng_Condition_A_REP2" = "A"
"LFQ_Astral_DIA_15min_50ng_Condition_A_REP3" = "A"
"LFQ_Astral_DIA_15min_50ng_Condition_B_REP1" = "B"
"LFQ_Astral_DIA_15min_50ng_Condition_B_REP2" = "B"
"LFQ_Astral_DIA_15min_50ng_Condition_B_REP3" = "B"

[run_mapper]
"LFQ_Astral_DIA_15min_50ng_Condition_A_REP1" = "Condition_A_Sample_Alpha_01"
"LFQ_Astral_DIA_15min_50ng_Condition_A_REP2" = "Condition_A_Sample_Alpha_02"
"LFQ_Astral_DIA_15min_50ng_Condition_A_REP3" = "Condition_A_Sample_Alpha_03"
"LFQ_Astral_DIA_15min_50ng_Condition_B_REP1" = "Condition_B_Sample_Alpha_01"
"LFQ_Astral_DIA_15min_50ng_Condition_B_REP2" = "Condition_B_Sample_Alpha_02"
"LFQ_Astral_DIA_15min_50ng_Condition_B_REP3" = "Condition_B_Sample_Alpha_03"

[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[modifications_parser]
"parse_column" = "Sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern" = "\\(([^()]*)\\)"
"modification_dict" = {"(unimod:35)" = "Oxidation", "(unimod:1)" = "Acetyl", "(unimod:4)" = "Carbamidomethyl"}

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = true
