[mapper]
"Accession" = "Proteins"
"Peptide" = "Sequence"
"z" = "Charge"

[condition_mapper]
"IO08_140SPD_HYEA_QC_B13 Normalized Area" = "B"
"IO08_140SPD_HYEA_QC_B14 Normalized Area" = "B"
"IO08_140SPD_HYEA_QC_B15 Normalized Area" = "B"
"IO08_140SPD_HYEA_QC_B16 Normalized Area" = "B"
"IO08_140SPD_HYEA_QC_B17 Normalized Area" = "B"
"IO08_140SPD_HYEA_QC_B18 Normalized Area" = "B"
"IO08_140SPD_HYEA_QC_B19 Normalized Area" = "B"
"IO08_140SPD_HYEA_QC_B20 Normalized Area" = "B"
"IO08_140SPD_HYEA_QC_B21 Normalized Area" = "B"
"IO08_140SPD_HYEA_QC_B22 Normalized Area" = "B"
"IO08_140SPD_HYEA_QC_B23 Normalized Area" = "B"
"IO08_140SPD_HYEB_QC_O10 Normalized Area" = "A"
"IO08_140SPD_HYEB_QC_O11 Normalized Area" = "A"
"IO08_140SPD_HYEB_QC_O12 Normalized Area" = "A"
"IO08_140SPD_HYEB_QC_O2 Normalized Area" = "A"
"IO08_140SPD_HYEB_QC_O3 Normalized Area" = "A"
"IO08_140SPD_HYEB_QC_O4 Normalized Area" = "A"
"IO08_140SPD_HYEB_QC_O5 Normalized Area" = "A"
"IO08_140SPD_HYEB_QC_O6 Normalized Area" = "A"
"IO08_140SPD_HYEB_QC_O7 Normalized Area" = "A"
"IO08_140SPD_HYEB_QC_O8 Normalized Area" = "A"
"IO08_140SPD_HYEB_QC_O9 Normalized Area" = "A"

[run_mapper]

[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[modifications_parser]
"parse_column" = "Sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern"="(?<=\\().+?(?=\\))"
"modification_dict" = {"+57.02" = "Carbamidomethyl", "+15.99" = "Oxidation", "-17.026548" = "Gln->pyro-Glu", "-18.010565" = "Glu->pyro-Glu", "+42.01" = "Acetyl"}

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = false
