[mapper]
"Modified.Sequence" = "Sequence"
"Run" = "Raw file"
"Protein.Names" = "Proteins"
"Precursor.Charge" = "Charge"
"Precursor.Quantity" = "Intensity"

[condition_mapper]
"IO08_140SPD_HYEA_QC_B13" = "B"
"IO08_140SPD_HYEA_QC_B14" = "B"
"IO08_140SPD_HYEA_QC_B15" = "B"
"IO08_140SPD_HYEA_QC_B16" = "B"
"IO08_140SPD_HYEA_QC_B17" = "B"
"IO08_140SPD_HYEA_QC_B18" = "B"
"IO08_140SPD_HYEA_QC_B19" = "B"
"IO08_140SPD_HYEA_QC_B20" = "B"
"IO08_140SPD_HYEA_QC_B21" = "B"
"IO08_140SPD_HYEA_QC_B22" = "B"
"IO08_140SPD_HYEA_QC_B23" = "B"
"IO08_140SPD_HYEB_QC_O10" = "A"
"IO08_140SPD_HYEB_QC_O11" = "A"
"IO08_140SPD_HYEB_QC_O12" = "A"
"IO08_140SPD_HYEB_QC_O2" = "A"
"IO08_140SPD_HYEB_QC_O3" = "A"
"IO08_140SPD_HYEB_QC_O4" = "A"
"IO08_140SPD_HYEB_QC_O5" = "A"
"IO08_140SPD_HYEB_QC_O6" = "A"
"IO08_140SPD_HYEB_QC_O7" = "A"
"IO08_140SPD_HYEB_QC_O8" = "A"
"IO08_140SPD_HYEB_QC_O9" = "A"

[run_mapper]

[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[modifications_parser]
"parse_column" = "Sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern" = "\\(([^()]*)\\)"
"modification_dict" = {"(unimod:35)" = "Oxidation", "(unimod:1)" = "Acetyl", "(unimod:4)" = "Carbamidomethyl"}

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = true
